# Generated by Django 3.1 on 2020-09-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
